app/urls.py
# app/urls.py

from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
        path('index/', views.index, name='index'),
        path('detail/<int:pk>/', views.detail, name='detail'),
        path('', views.upload, name='upload'),
]

config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# 開発環境での設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/detail.html
<!-- app/templates/app/detail.html -->

<!doctype html>
<html>
        <head>
                <title>テストアプリ</title>
        </head>
        <body>

            <h2>CSVファイル</h2>
            <br>

            <a href="{% url 'app:index' %}">戻る</a>
            <br>

            <!-- 各インスタンス属性の要素を取得 -->
            <p>アップロード日：{{ file_value.created_at }}</p>
            <p>ダウンロード：<a href="{{ file_value.upload_dir.url }}">{{file_value.file_name }}</a></p>
            <br>

            <!-- 読み込んだCSVファイルをテーブル形式で表示 -->
            <table border="1">
                <tr>
                    <td>index</td>
                    {% for columns, item in df.iteritems %}
                        <th>{{ columns }}</th>
                    {% endfor %}
                </tr>
                {% for index, rows in df.iterrows %}
                    <tr>
                        <th>{{ index }}</th>
                        {% for row in rows %}
                            <td>{{ row }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>

        </body>
</html>

app/templates/app/index.html
<!-- app/templates/app/index.html -->

<!doctype html>
<html>
        <head>
                <title>テストアプリ</title>
        </head>
        <body>

            <h2>CSVファイルリスト</h2>
            <br>

            {% if file_obj %}
                {% for file in file_obj %}
                    <p>
                        {{ file.created_at }}
                         {{ file.title }}
                        <a href="{% url 'app:detail' pk=file.id %}">詳細</a>
                    </p>
                {% endfor %}
            {% else %}
                <h2>現在ファイルはありません</h2>
            {% endif %}

        </body>
</html>

app/templates/app/upload.html
<html>
<body>
    <form class="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>施設名: <input type="char" name="char" value="" required></p>
        <p>CSV: <input type="file" name="csv" value="" required></p>
        <p><input type="submit" name="btn_upload" value="UPLOAD"></p>
    </form>
    <table border="1">
        <tr>
            <td>index</td>
            {% for columns, item in df.iteritems %}
                <th>{{ columns }}</th>
            {% endfor %}
        </tr>
        {% for index, rows in df.iterrows %}
            <tr>
                <th>{{ index }}</th>
                {% for row in rows %}
                    <td>{{ row }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </table>
        <h1>重要意見 + 類似ツイート</h1>
        {% for key, r_url in r_urls.items %}
            <h2>{{key}}</h2>
            {% for list in r_url %}
                {% for opinion, urls in list.items %}
                    <h3>{{ opinion }}</h3>
                    {% for url in urls %}
                    <blockquote class="twitter-tweet">
                        (ツイート埋め込み処理中)
                        <a href="{{ url }}">tweet</a>
                    </blockquote>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>{% endfor %}{% endfor %}
            {% endfor %}
        {% endfor %}
</body>
</html>